name: Build And Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: |
          docker rm -f movie-watchlist || true

      - name: Build Image
        run: |
          docker build -t movie-watchlist-app .

      - name: Run Container
        run: |
          docker run -d --name movie-watchlist -p 8020:8020 movie-watchlist-app